import Head from "next/head";
import { Inter } from "@next/font/google";
import MainImageDisplay from "../components/MainImageDisplay/MainImageDisplay";
import GraphicTshirts from "../components/GraphicTshirts/GraphicTshirts";
import NewArrivals from "../components/NewArrivals/NewArrivals";
import FootballJerseys from "../components/FootballJerseys/FootballJerseys";
import Cover from "../components/PhoneCases/Cover";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>FootballMonk.in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainImageDisplay />
      <GraphicTshirts />
      <NewArrivals />
      <FootballJerseys />
      <Cover />
    </>
  );
}
